
services:
  influxdb2:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ORG=sensor_integration
      - DOCKER_INFLUXDB_INIT_USERNAME=ggia
      - DOCKER_INFLUXDB_INIT_PASSWORD=egoeimai7
    volumes:
      - influxdb2_data:/var/lib/influxdb2
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ggia
      - RABBITMQ_DEFAULT_PASS=egoeimai7

volumes:
  influxdb2_data: